package vistas;

import accesoADatos.ComidaData;
import accesoADatos.DietaComidaData;
import accesoADatos.DietaData;
import accesoADatos.PacienteData;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.TimerTask;
import javafx.scene.paint.Color;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.border.EmptyBorder;

public class MenuView extends javax.swing.JFrame {
static PacienteData pData = new PacienteData();
static DietaData dData = new DietaData();
static ComidaData cData = new ComidaData();
static DietaComidaData dCData = new DietaComidaData();
static PacienteFormulario pF = new PacienteFormulario();
static PacienteInforme pI = new PacienteInforme();
static PacienteConsulta pC = new PacienteConsulta();
static ComidaRegistro cR = new ComidaRegistro();
static ComidaInformacion cI = new ComidaInformacion();
static DietaRegistro dR = new DietaRegistro();
static DietaInformacion dI = new DietaInformacion();
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        generarResumen();
        fechaHoy();
        inicioColores();
        toggleMenu();
        agregarAlContenedor();
    }
    
    public void generarResumen(){
        List pA = pData.listarPacientesConDieta();
        jTPacienteActivos.setText(pA.size()+"");
        List pE = dCData.listarPacientesExitosos();
        jLPacientesExitosos.setText(pE.size()+"");
        List pSE = dCData.listarPacientesSinExito();
        jLSinExito.setText(pSE.size()+"");
        //----------------------------------
        List dA = dData.listarDietas();
        jLDietasActivas.setText(dA.size()+"");
        List dE = dData.listarDietasExitosas();
        jLDietasExitosas.setText(dE.size()+"");
        List dSE = dData.listarDietasSinExito();
        jLDietasSExitosas.setText(dSE.size()+"");
        //----------------------------------
        List cA = cData.listarComida();
        jLComidaActivas.setText(cA.size()+"");
        List cE = cData.buscarCaloriasMax(500);   // Buscar comidas con mayor calorias?
        jLComidaExitosa.setText(cE.size()+"");
        List cSE = cData.buscarCaloriasMin(500);
        jLComidaSExito.setText(cSE.size()+"");
        
    }
    
    private void inicioColores(){
        jBComidas.setBackground(new java.awt.Color(65,193,186));
        jBDietas.setBackground(new java.awt.Color(65,193,186));
        jBInicio.setBackground(new java.awt.Color(65,193,186));
        jBPacientes.setBackground(new java.awt.Color(65,193,186));
        jPToggleMenu.setBackground(new java.awt.Color(31,213,181)); 
        
    }
    
    public void toggleMenu(){
        jPToggleMenu.setVisible(true);
        limpiarMenu();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JPanel();
        jPPresentacion = new javax.swing.JPanel();
        jLFecha1 = new javax.swing.JLabel();
        Contenedor = new javax.swing.JPanel();
        jPToggleMenu = new javax.swing.JPanel();
        jBFPacientes = new javax.swing.JButton();
        jBFComida = new javax.swing.JButton();
        jBIPacientes = new javax.swing.JButton();
        jBLComida = new javax.swing.JButton();
        jBRDieta = new javax.swing.JButton();
        jBLDieta = new javax.swing.JButton();
        jLIndicadorMenu = new javax.swing.JLabel();
        jLIndicadorNombre = new javax.swing.JLabel();
        jTContDatosComida = new javax.swing.JPanel();
        jLTituloComida = new javax.swing.JLabel();
        jLComidaActivas = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLComidaExitosa = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLComidaSExito = new javax.swing.JLabel();
        jTContDatosDieta = new javax.swing.JPanel();
        jLTituloDieta = new javax.swing.JLabel();
        jLDietasActivas = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLDietasExitosas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLDietasSExitosas = new javax.swing.JLabel();
        jTContDatosPaciente = new javax.swing.JPanel();
        jLTituloPaciente = new javax.swing.JLabel();
        jTPacienteActivos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelEP = new javax.swing.JLabel();
        jLPacientesExitosos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLSinExito = new javax.swing.JLabel();
        jPMenu = new javax.swing.JPanel();
        jBInicio = new javax.swing.JButton();
        jBPacientes = new javax.swing.JButton();
        jBComidas = new javax.swing.JButton();
        jBDietas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Escritorio.setBackground(new java.awt.Color(65, 193, 186));
        Escritorio.setPreferredSize(new java.awt.Dimension(830, 520));

        jPPresentacion.setBackground(new java.awt.Color(65, 193, 186));
        jPPresentacion.setPreferredSize(new java.awt.Dimension(420, 55));

        jLFecha1.setBackground(new java.awt.Color(153, 153, 153));
        jLFecha1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLFecha1.setText("Hoy es {dia}, de {mes} de {anio}");

        javax.swing.GroupLayout jPPresentacionLayout = new javax.swing.GroupLayout(jPPresentacion);
        jPPresentacion.setLayout(jPPresentacionLayout);
        jPPresentacionLayout.setHorizontalGroup(
            jPPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPresentacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPPresentacionLayout.setVerticalGroup(
            jPPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPresentacionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLFecha1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setPreferredSize(new java.awt.Dimension(730, 465));

        jPToggleMenu.setBackground(new java.awt.Color(65, 193, 186));
        jPToggleMenu.setPreferredSize(new java.awt.Dimension(730, 50));

        jBFPacientes.setBackground(new java.awt.Color(150, 150, 150));
        jBFPacientes.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBFPacientes.setText("Registro");
        jBFPacientes.setBorder(null);
        jBFPacientes.setBorderPainted(false);
        jBFPacientes.setContentAreaFilled(false);
        jBFPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBFPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBFPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBFPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBFPacientesMouseExited(evt);
            }
        });
        jBFPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFPacientesActionPerformed(evt);
            }
        });

        jBFComida.setBackground(new java.awt.Color(150, 150, 150));
        jBFComida.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBFComida.setText("Registro");
        jBFComida.setBorder(null);
        jBFComida.setBorderPainted(false);
        jBFComida.setContentAreaFilled(false);
        jBFComida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBFComida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBFComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBFComidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBFComidaMouseExited(evt);
            }
        });
        jBFComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFComidaActionPerformed(evt);
            }
        });

        jBIPacientes.setBackground(new java.awt.Color(150, 150, 150));
        jBIPacientes.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBIPacientes.setText("Informes");
        jBIPacientes.setBorder(null);
        jBIPacientes.setBorderPainted(false);
        jBIPacientes.setContentAreaFilled(false);
        jBIPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBIPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBIPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBIPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBIPacientesMouseExited(evt);
            }
        });
        jBIPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIPacientesActionPerformed(evt);
            }
        });

        jBLComida.setBackground(new java.awt.Color(150, 150, 150));
        jBLComida.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBLComida.setText("Listado");
        jBLComida.setBorder(null);
        jBLComida.setBorderPainted(false);
        jBLComida.setContentAreaFilled(false);
        jBLComida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLComida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBLComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLComidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLComidaMouseExited(evt);
            }
        });
        jBLComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLComidaActionPerformed(evt);
            }
        });

        jBRDieta.setBackground(new java.awt.Color(150, 150, 150));
        jBRDieta.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBRDieta.setText("Registro");
        jBRDieta.setBorder(null);
        jBRDieta.setBorderPainted(false);
        jBRDieta.setContentAreaFilled(false);
        jBRDieta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRDieta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBRDieta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBRDietaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBRDietaMouseExited(evt);
            }
        });
        jBRDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRDietaActionPerformed(evt);
            }
        });

        jBLDieta.setBackground(new java.awt.Color(150, 150, 150));
        jBLDieta.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBLDieta.setText("Listado");
        jBLDieta.setBorder(null);
        jBLDieta.setBorderPainted(false);
        jBLDieta.setContentAreaFilled(false);
        jBLDieta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLDieta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBLDieta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLDietaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLDietaMouseExited(evt);
            }
        });
        jBLDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLDietaActionPerformed(evt);
            }
        });

        jLIndicadorMenu.setBackground(new java.awt.Color(150, 150, 150));
        jLIndicadorMenu.setFont(new java.awt.Font("Agency FB", 3, 24)); // NOI18N
        jLIndicadorMenu.setForeground(new java.awt.Color(131, 249, 228));

        jLIndicadorNombre.setBackground(new java.awt.Color(150, 150, 150));
        jLIndicadorNombre.setFont(new java.awt.Font("Agency FB", 3, 36)); // NOI18N
        jLIndicadorNombre.setForeground(new java.awt.Color(131, 249, 228));

        javax.swing.GroupLayout jPToggleMenuLayout = new javax.swing.GroupLayout(jPToggleMenu);
        jPToggleMenu.setLayout(jPToggleMenuLayout);
        jPToggleMenuLayout.setHorizontalGroup(
            jPToggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPToggleMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPToggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFComida, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBFPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPToggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBIPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLComida, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLIndicadorMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPToggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPToggleMenuLayout.createSequentialGroup()
                    .addGap(292, 292, 292)
                    .addComponent(jLIndicadorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );
        jPToggleMenuLayout.setVerticalGroup(
            jPToggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPToggleMenuLayout.createSequentialGroup()
                .addGroup(jPToggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFComida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPToggleMenuLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPToggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBIPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPToggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBLComida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLIndicadorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBFPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPToggleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPToggleMenuLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLIndicadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTContDatosComida.setBackground(new java.awt.Color(255, 255, 255));
        jTContDatosComida.setFocusable(false);
        jTContDatosComida.setPreferredSize(new java.awt.Dimension(270, 170));

        jLTituloComida.setBackground(new java.awt.Color(65, 193, 186));
        jLTituloComida.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLTituloComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloComida.setText("Comidas");
        jLTituloComida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLTituloComida.setOpaque(true);
        jLTituloComida.setPreferredSize(new java.awt.Dimension(235, 33));

        jLComidaActivas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLComidaActivas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLComidaActivas.setText("**");
        jLComidaActivas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLComidaActivas.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel15.setBackground(new java.awt.Color(251, 230, 152));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Activos");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel16.setBackground(new java.awt.Color(251, 230, 152));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(" +500 kcal");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setOpaque(true);
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 50));

        jLComidaExitosa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLComidaExitosa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLComidaExitosa.setText("**");
        jLComidaExitosa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLComidaExitosa.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel17.setBackground(new java.awt.Color(251, 230, 152));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(" -500 kcal");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.setOpaque(true);
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 50));

        jLComidaSExito.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLComidaSExito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLComidaSExito.setText("**");
        jLComidaSExito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLComidaSExito.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jTContDatosComidaLayout = new javax.swing.GroupLayout(jTContDatosComida);
        jTContDatosComida.setLayout(jTContDatosComidaLayout);
        jTContDatosComidaLayout.setHorizontalGroup(
            jTContDatosComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTituloComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jTContDatosComidaLayout.createSequentialGroup()
                .addGroup(jTContDatosComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTContDatosComidaLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jTContDatosComidaLayout.createSequentialGroup()
                        .addComponent(jLComidaExitosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jLComidaActivas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jTContDatosComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLComidaSExito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jTContDatosComidaLayout.setVerticalGroup(
            jTContDatosComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTContDatosComidaLayout.createSequentialGroup()
                .addComponent(jLTituloComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jTContDatosComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jTContDatosComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLComidaExitosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLComidaActivas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLComidaSExito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jTContDatosDieta.setBackground(new java.awt.Color(255, 255, 255));
        jTContDatosDieta.setFocusable(false);
        jTContDatosDieta.setPreferredSize(new java.awt.Dimension(270, 170));

        jLTituloDieta.setBackground(new java.awt.Color(65, 193, 186));
        jLTituloDieta.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLTituloDieta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloDieta.setText("Dieta");
        jLTituloDieta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLTituloDieta.setOpaque(true);
        jLTituloDieta.setPreferredSize(new java.awt.Dimension(235, 33));

        jLDietasActivas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLDietasActivas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDietasActivas.setText("**");
        jLDietasActivas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLDietasActivas.setMaximumSize(null);
        jLDietasActivas.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel12.setBackground(new java.awt.Color(251, 230, 152));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Activos");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setMaximumSize(null);
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel13.setBackground(new java.awt.Color(251, 230, 152));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Exitosos");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setMaximumSize(null);
        jLabel13.setOpaque(true);
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 50));

        jLDietasExitosas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLDietasExitosas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDietasExitosas.setText("**");
        jLDietasExitosas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLDietasExitosas.setMaximumSize(null);
        jLDietasExitosas.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel14.setBackground(new java.awt.Color(251, 230, 152));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sin Exito");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setMaximumSize(null);
        jLabel14.setOpaque(true);
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 50));

        jLDietasSExitosas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLDietasSExitosas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDietasSExitosas.setText("**");
        jLDietasSExitosas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLDietasSExitosas.setMaximumSize(null);
        jLDietasSExitosas.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jTContDatosDietaLayout = new javax.swing.GroupLayout(jTContDatosDieta);
        jTContDatosDieta.setLayout(jTContDatosDietaLayout);
        jTContDatosDietaLayout.setHorizontalGroup(
            jTContDatosDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTituloDieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jTContDatosDietaLayout.createSequentialGroup()
                .addGroup(jTContDatosDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLDietasExitosas, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jTContDatosDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDietasActivas, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jTContDatosDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLDietasSExitosas, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
        );
        jTContDatosDietaLayout.setVerticalGroup(
            jTContDatosDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTContDatosDietaLayout.createSequentialGroup()
                .addComponent(jLTituloDieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jTContDatosDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jTContDatosDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDietasExitosas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLDietasActivas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLDietasSExitosas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        jTContDatosPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jTContDatosPaciente.setFocusable(false);
        jTContDatosPaciente.setPreferredSize(new java.awt.Dimension(270, 170));

        jLTituloPaciente.setBackground(new java.awt.Color(65, 193, 186));
        jLTituloPaciente.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLTituloPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloPaciente.setText("Pacientes");
        jLTituloPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLTituloPaciente.setOpaque(true);
        jLTituloPaciente.setPreferredSize(new java.awt.Dimension(235, 33));

        jTPacienteActivos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTPacienteActivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTPacienteActivos.setText("**");
        jTPacienteActivos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTPacienteActivos.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel5.setBackground(new java.awt.Color(251, 230, 152));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Activos");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabelEP.setBackground(new java.awt.Color(251, 230, 152));
        jLabelEP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEP.setText("Exitosos");
        jLabelEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelEP.setOpaque(true);
        jLabelEP.setPreferredSize(new java.awt.Dimension(100, 50));

        jLPacientesExitosos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLPacientesExitosos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPacientesExitosos.setText("**");
        jLPacientesExitosos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLPacientesExitosos.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel7.setBackground(new java.awt.Color(251, 230, 152));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sin Exito");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 50));

        jLSinExito.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLSinExito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSinExito.setText("**");
        jLSinExito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLSinExito.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jTContDatosPacienteLayout = new javax.swing.GroupLayout(jTContDatosPaciente);
        jTContDatosPaciente.setLayout(jTContDatosPacienteLayout);
        jTContDatosPacienteLayout.setHorizontalGroup(
            jTContDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTituloPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jTContDatosPacienteLayout.createSequentialGroup()
                .addGroup(jTContDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEP, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLPacientesExitosos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jTContDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPacienteActivos, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jTContDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSinExito, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jTContDatosPacienteLayout.setVerticalGroup(
            jTContDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTContDatosPacienteLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLTituloPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGroup(jTContDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEP, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jTContDatosPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPacientesExitosos, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jTPacienteActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLSinExito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPToggleMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTContDatosPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTContDatosComida, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jTContDatosDieta, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addComponent(jPToggleMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTContDatosDieta, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTContDatosComida, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jTContDatosPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPMenu.setBackground(new java.awt.Color(65, 193, 186));
        jPMenu.setOpaque(false);
        jPMenu.setPreferredSize(new java.awt.Dimension(100, 520));

        jBInicio.setBackground(new java.awt.Color(65, 193, 186));
        jBInicio.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBInicio.setForeground(new java.awt.Color(65, 193, 186));
        jBInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/logo44.png"))); // NOI18N
        jBInicio.setBorder(null);
        jBInicio.setBorderPainted(false);
        jBInicio.setContentAreaFilled(false);
        jBInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBInicio.setInheritsPopupMenu(true);
        jBInicio.setPreferredSize(new java.awt.Dimension(50, 50));
        jBInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBInicioMouseExited(evt);
            }
        });
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });

        jBPacientes.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/icn persona (1).png"))); // NOI18N
        jBPacientes.setBorder(null);
        jBPacientes.setBorderPainted(false);
        jBPacientes.setContentAreaFilled(false);
        jBPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBPacientes.setPreferredSize(new java.awt.Dimension(50, 50));
        jBPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBPacientesMouseExited(evt);
            }
        });
        jBPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPacientesActionPerformed(evt);
            }
        });

        jBComidas.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBComidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/icn comida (1).png"))); // NOI18N
        jBComidas.setToolTipText("");
        jBComidas.setBorder(null);
        jBComidas.setBorderPainted(false);
        jBComidas.setContentAreaFilled(false);
        jBComidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBComidas.setPreferredSize(new java.awt.Dimension(50, 50));
        jBComidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBComidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBComidasMouseExited(evt);
            }
        });
        jBComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBComidasActionPerformed(evt);
            }
        });

        jBDietas.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jBDietas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/icn dieta.png"))); // NOI18N
        jBDietas.setBorder(null);
        jBDietas.setBorderPainted(false);
        jBDietas.setContentAreaFilled(false);
        jBDietas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBDietas.setPreferredSize(new java.awt.Dimension(50, 50));
        jBDietas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBDietasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBDietasMouseExited(evt);
            }
        });
        jBDietas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDietasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPMenuLayout = new javax.swing.GroupLayout(jPMenu);
        jPMenu.setLayout(jPMenuLayout);
        jPMenuLayout.setHorizontalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBDietas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addComponent(jBComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPMenuLayout.setVerticalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addComponent(jBInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jBPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDietas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addComponent(jPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))
                    .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addComponent(jPPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
            .addComponent(jPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBComidasActionPerformed
        jLIndicadorNombre.setVisible(false);
        jLIndicadorMenu.setVisible(true);
        if (jPToggleMenu.isVisible() ) {            
//            if(jBFComida.isVisible()){
//                jPToggleMenu.setVisible(false);
//            } else {
                jBFPacientes.setVisible(false);
                jBIPacientes.setVisible(false);
                jBLDieta.setVisible(false);
                jBRDieta.setVisible(false);
                jBFComida.setVisible(true);
                jBLComida.setVisible(true);
            //}
        } else{
            jPToggleMenu.setVisible(true);
            jBFPacientes.setVisible(false);
            jBIPacientes.setVisible(false);
            jBLDieta.setVisible(false);
            jBRDieta.setVisible(false);
            jBFComida.setVisible(true);
            jBLComida.setVisible(true);
        }
        jLIndicadorMenu.setText("Registro y Consultas de Comida");
//         superponerPanel(cR);

    }//GEN-LAST:event_jBComidasActionPerformed

    private void jBDietasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDietasActionPerformed
        jLIndicadorNombre.setVisible(false);
        jLIndicadorMenu.setVisible(true);
        if (jPToggleMenu.isVisible() ) {            
//            if(jBRDieta.isVisible()){
//                jPToggleMenu.setVisible(false);
//            } else {
                jBFPacientes.setVisible(false);
                jBIPacientes.setVisible(false);
                jBLDieta.setVisible(true);
                jBRDieta.setVisible(true);
                jBFComida.setVisible(false);
                jBLComida.setVisible(false);
                
            //}
        } else{
            jPToggleMenu.setVisible(true);
            jBFPacientes.setVisible(false);
            jBIPacientes.setVisible(false);
            jBLDieta.setVisible(true);
            jBRDieta.setVisible(true);
            jBFComida.setVisible(false);
            jBLComida.setVisible(false);
        }
        jLIndicadorMenu.setText("Registro y Consultas de Dieta");
//        superponerPanel(dR);
//        dR.cargarCombo();
    }//GEN-LAST:event_jBDietasActionPerformed

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        pC.dispose();
        pF.dispose();
        pI.dispose();
        cI.dispose();
        cR.dispose();
        dI.dispose();
        dR.dispose();
       // jLIndicadorMenu.setText("");
        jTContDatosPaciente.setVisible(true);
        jTContDatosComida.setVisible(true);
        jTContDatosDieta.setVisible(true);
        generarResumen();
        jPToggleMenu.setVisible(true); 
        // aca
        limpiarMenu();
        
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBLDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLDietaActionPerformed
        superponerPanel(dI);
    }//GEN-LAST:event_jBLDietaActionPerformed

    private void jBRDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRDietaActionPerformed
        superponerPanel(dR);
        dR.cargarCombo();
    }//GEN-LAST:event_jBRDietaActionPerformed

    private void jBLComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLComidaActionPerformed
        superponerPanel(cI);
    }//GEN-LAST:event_jBLComidaActionPerformed

    private void jBIPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIPacientesActionPerformed
        superponerPanel(pI);
    }//GEN-LAST:event_jBIPacientesActionPerformed

    private void jBFComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFComidaActionPerformed
        superponerPanel(cR);
    }//GEN-LAST:event_jBFComidaActionPerformed

    private void jBFPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFPacientesActionPerformed
        superponerPanel(pF);
        pF.cargarCombo();
    }//GEN-LAST:event_jBFPacientesActionPerformed

    private void jBInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInicioMouseEntered
        jBInicio.setContentAreaFilled(true);
        jBInicio.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBInicioMouseEntered

    private void jBComidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBComidasMouseEntered
        jBComidas.setBackground(new java.awt.Color(96,235,227));
        jBComidas.setContentAreaFilled(true);
    }//GEN-LAST:event_jBComidasMouseEntered

    private void jBDietasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDietasMouseEntered
        jBDietas.setBackground(new java.awt.Color(96,235,227));
        jBDietas.setContentAreaFilled(true);
    }//GEN-LAST:event_jBDietasMouseEntered

    private void jBInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInicioMouseExited
        jBInicio.setContentAreaFilled(false);
        jBInicio.setBackground(new java.awt.Color(65,193,186));
    }//GEN-LAST:event_jBInicioMouseExited

    private void jBComidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBComidasMouseExited
        jBComidas.setBackground(new java.awt.Color(65,193,186));
        jBComidas.setContentAreaFilled(false);
    }//GEN-LAST:event_jBComidasMouseExited

    private void jBDietasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDietasMouseExited
        jBDietas.setBackground(new java.awt.Color(65,193,186));
        jBDietas.setContentAreaFilled(false);
    }//GEN-LAST:event_jBDietasMouseExited

    private void jBFPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFPacientesMouseEntered
        jBFPacientes.setContentAreaFilled(true);
        jBFPacientes.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBFPacientesMouseEntered

    private void jBFComidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFComidaMouseEntered
        jBFComida.setContentAreaFilled(true);
        jBFComida.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBFComidaMouseEntered

    private void jBIPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBIPacientesMouseEntered
        jBIPacientes.setContentAreaFilled(true);
        jBIPacientes.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBIPacientesMouseEntered

    private void jBLComidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLComidaMouseEntered
        jBLComida.setContentAreaFilled(true);
        jBLComida.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBLComidaMouseEntered

    private void jBRDietaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRDietaMouseEntered
        jBRDieta.setContentAreaFilled(true);
        jBRDieta.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBRDietaMouseEntered

    private void jBLDietaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLDietaMouseEntered
        jBLDieta.setContentAreaFilled(true);
        jBLDieta.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBLDietaMouseEntered

    private void jBFPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFPacientesMouseExited
        jBFPacientes.setContentAreaFilled(false);
        jBFPacientes.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBFPacientesMouseExited

    private void jBFComidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFComidaMouseExited
        jBFComida.setContentAreaFilled(false);
        jBFComida.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBFComidaMouseExited

    private void jBIPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBIPacientesMouseExited
        jBIPacientes.setContentAreaFilled(false);
        jBIPacientes.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBIPacientesMouseExited

    private void jBLComidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLComidaMouseExited
        jBLComida.setContentAreaFilled(false);
        jBLComida.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBLComidaMouseExited

    private void jBRDietaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRDietaMouseExited
        jBRDieta.setContentAreaFilled(false);
        jBRDieta.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBRDietaMouseExited

    private void jBLDietaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLDietaMouseExited
        jBLDieta.setContentAreaFilled(false);
        jBLDieta.setBackground(new java.awt.Color(96,235,227));
    }//GEN-LAST:event_jBLDietaMouseExited

    private void jBPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPacientesActionPerformed
        jLIndicadorNombre.setVisible(false);
        jLIndicadorMenu.setVisible(true);
        if (jPToggleMenu.isVisible() ) {
            //            if(jBFPacientes.isVisible()){
                //                jPToggleMenu.setVisible(false);
                //            } else {
                jBFPacientes.setVisible(true);
                jBIPacientes.setVisible(true);
                jBFComida.setVisible(false);
                jBLComida.setVisible(false);
                jBLDieta.setVisible(false);
                jBRDieta.setVisible(false);
                //}

        } else{
            jPToggleMenu.setVisible(true);
            jBFPacientes.setVisible(true);
            jBIPacientes.setVisible(true);
            jBFComida.setVisible(false);
            jBLComida.setVisible(false);
            jBLDieta.setVisible(false);
            jBRDieta.setVisible(false);
        }
        jLIndicadorMenu.setText("Registro y Consultas de Paciente");
        //        superponerPanel(pF);
        //        pF.cargarCombo();
    }//GEN-LAST:event_jBPacientesActionPerformed

    private void jBPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPacientesMouseExited
        jBPacientes.setBackground(new java.awt.Color(65,193,186));
        jBPacientes.setContentAreaFilled(false);
    }//GEN-LAST:event_jBPacientesMouseExited

    private void jBPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPacientesMouseEntered
        jBPacientes.setBackground(new java.awt.Color(96,235,227));
        jBPacientes.setContentAreaFilled(true);
    }//GEN-LAST:event_jBPacientesMouseEntered
    private void fechaHoy(){
        LocalDate hoy = LocalDate.now();
        int anio = hoy.getYear();
        int dia = hoy.getDayOfMonth();
        int mes = hoy.getMonthValue();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        jLFecha1.setText("Hoy es " + dia + " de " + meses[mes - 1] + " de " + anio);
        // Obtener la hora actual
        Calendar fecha = new GregorianCalendar();
        String hora = Integer.toString(fecha.get(Calendar.HOUR_OF_DAY));
        String minutos = Integer.toString(fecha.get(Calendar.MINUTE));
        String segundos = Integer.toString(fecha.get(Calendar.SECOND));
        //jLFecha.setText( hora +":" +minutos+":"+segundos);

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel Escritorio;
    private javax.swing.JButton jBComidas;
    private javax.swing.JButton jBDietas;
    private javax.swing.JButton jBFComida;
    private javax.swing.JButton jBFPacientes;
    private javax.swing.JButton jBIPacientes;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBLComida;
    private javax.swing.JButton jBLDieta;
    private javax.swing.JButton jBPacientes;
    private javax.swing.JButton jBRDieta;
    private javax.swing.JLabel jLComidaActivas;
    private javax.swing.JLabel jLComidaExitosa;
    private javax.swing.JLabel jLComidaSExito;
    private javax.swing.JLabel jLDietasActivas;
    private javax.swing.JLabel jLDietasExitosas;
    private javax.swing.JLabel jLDietasSExitosas;
    private javax.swing.JLabel jLFecha1;
    private javax.swing.JLabel jLIndicadorMenu;
    private javax.swing.JLabel jLIndicadorNombre;
    private javax.swing.JLabel jLPacientesExitosos;
    private javax.swing.JLabel jLSinExito;
    private javax.swing.JLabel jLTituloComida;
    private javax.swing.JLabel jLTituloDieta;
    private javax.swing.JLabel jLTituloPaciente;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEP;
    private javax.swing.JPanel jPMenu;
    private javax.swing.JPanel jPPresentacion;
    private javax.swing.JPanel jPToggleMenu;
    private javax.swing.JPanel jTContDatosComida;
    private javax.swing.JPanel jTContDatosDieta;
    private javax.swing.JPanel jTContDatosPaciente;
    private javax.swing.JLabel jTPacienteActivos;
    // End of variables declaration//GEN-END:variables

    private void superponerPanel(JInternalFrame panelInterno){ // cambiar por un SwitchCase
        jTContDatosPaciente.setVisible(false);
        jTContDatosComida.setVisible(false);
        jTContDatosDieta.setVisible(false);
        if (panelInterno.equals(pF)) {
            pI.dispose();
            cI.dispose();
            cR.dispose();
            dR.dispose();
            dI.dispose();
        } else if (panelInterno.equals(pI)) {
            pF.dispose();
            cI.dispose();
            cR.dispose();
            dR.dispose();
            dI.dispose();
        } else if (panelInterno.equals(cR)){
            pF.dispose();
            pI.dispose();
            cI.dispose();
            dR.dispose();
            dI.dispose();
        } else if (panelInterno.equals(cI)) {
            pF.dispose();
            pI.dispose();
            pC.dispose();
            cR.dispose();
            dR.dispose();
            dI.dispose();
        } else if (panelInterno.equals(dR)) {
            pF.dispose();
            pI.dispose();
            cR.dispose();
            cI.dispose();
            dI.dispose();
        } else if (panelInterno.equals(dI)) {
            pF.dispose();
            pI.dispose();
            cR.dispose();
            cI.dispose();
            dR.dispose();
        }
            
        panelInterno.setLocation(0, 53);
        panelInterno.setVisible(true);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) panelInterno.getUI()).setNorthPane(null);
        panelInterno.moveToFront();
        panelInterno.toFront();
    }
   
    private void agregarAlContenedor(){
        Contenedor.add(pF);
        Contenedor.add(pC);
        Contenedor.add(pI);
        Contenedor.add(cR);
        Contenedor.add(cI);
        Contenedor.add(dI);
        Contenedor.add(dR);
    }
    
    private void limpiarMenu () {
        jBRDieta.setVisible(false);
        jBFPacientes.setVisible(false);
        jBFComida.setVisible(false);
        jBLDieta.setVisible(false);
        jBLComida.setVisible(false);
        jBIPacientes.setVisible(false);
        jLIndicadorMenu.setVisible(false);
        jLIndicadorNombre.setVisible(true);
        jLIndicadorNombre.setText("NutriSalud");
    }
    
}
