/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.DietaComidaData;
import accesoADatos.DietaData;
import accesoADatos.PacienteData;
import entidades.Dieta;
import entidades.Paciente;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PacienteInforme extends javax.swing.JInternalFrame {

    static PacienteData pD = new PacienteData();
    static DietaComidaData dCD = new DietaComidaData();
    static DietaData dD = new DietaData();

    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    
    public PacienteInforme() {
        initComponents();
        cargarCabeceras();
    }

    private void cargarCabeceras() {
        modelo.addColumn("Nombre");
        modelo.addColumn("DNI");
        modelo.addColumn("Telefono");
        modelo.addColumn("Estado");
        modelo.addColumn("Fecha Inicio");
        modelo.addColumn("Fecha Final");
        modelo.addColumn("Nombre Dieta");
        jTPInforme.setModel(modelo);
    }

    public void borrarFilas() {

        int f = jTPInforme.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTPInforme = new javax.swing.JTable();
        jRBPacienteE = new javax.swing.JRadioButton();
        jRBPacientesS = new javax.swing.JRadioButton();
        jRBPacientesP = new javax.swing.JRadioButton();
        jBSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(730, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTPInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTPInforme);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 710, 310));

        jRBPacienteE.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jRBPacienteE.setText("Pacientes exitosos");
        jRBPacienteE.setBorder(null);
        jRBPacienteE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPacienteEActionPerformed(evt);
            }
        });
        getContentPane().add(jRBPacienteE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jRBPacientesS.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jRBPacientesS.setText("Pacientes sin Exito");
        jRBPacientesS.setBorder(null);
        jRBPacientesS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPacientesSActionPerformed(evt);
            }
        });
        getContentPane().add(jRBPacientesS, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jRBPacientesP.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jRBPacientesP.setText("Pacientes en progreso");
        jRBPacientesP.setBorder(null);
        jRBPacientesP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPacientesPActionPerformed(evt);
            }
        });
        getContentPane().add(jRBPacientesP, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jBSalir.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11)); // NOI18N
        jBSalir.setText("X");
        jBSalir.setBorder(null);
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.setFocusPainted(false);
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBSalirMouseExited(evt);
            }
        });
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 25, 26));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Informe de Paciente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/fondo azul 2.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(730, 450));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBPacienteEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPacienteEActionPerformed
        try {
            borrarFilas();
            //Setea el otro radio en falso
            jRBPacientesS.setSelected(false);
            jRBPacientesP.setSelected(false);
            //Iterar sobre pacientes exitosos
            List<Paciente> pExitosos = dCD.listarPacientesExitosos();
            for (Paciente pExitoso : pExitosos ) {
                //Obtener la dieta exitosa de cada paciente
                Dieta dieta = dD.buscarDietaXPaciente(pExitoso.getIdPaciente());
                //
                modelo.addRow(new Object[]{pExitoso.getNombre(), pExitoso.getDni(), pExitoso.getTelefono(), dD.buscarDietaXPaciente(pExitoso.getIdPaciente()).finalizado() ? "En progreso" : "Finalizado", dieta.getFechaInicial(), dieta.getFechaFinal(), dieta.getNombre()});
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla");
        }

    }//GEN-LAST:event_jRBPacienteEActionPerformed

    private void jRBPacientesSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPacientesSActionPerformed
        try {
            borrarFilas();
            jRBPacienteE.setSelected(false);
            jRBPacientesP.setSelected(false);
            for (Paciente pSExito : dCD.listarPacientesSinExito()) {
                Dieta dieta = dD.buscarDietaXPaciente(pSExito.getIdPaciente());
                modelo.addRow(new Object[]{pSExito.getNombre(), pSExito.getDni(), pSExito.getTelefono(), dD.buscarDietaXPaciente(pSExito.getIdPaciente()).finalizado() ? "En progreso" : "Finalizado", dieta.getFechaInicial(), dieta.getFechaFinal(),  dieta.getNombre()});
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla");
        }
    }//GEN-LAST:event_jRBPacientesSActionPerformed

    private void jRBPacientesPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPacientesPActionPerformed
        try {
            borrarFilas();
            jRBPacienteE.setSelected(false);
            jRBPacientesS.setSelected(false);
            for (Dieta dieta : dD.listarTodasLasDietas()) {
                if(!dieta.finalizado()){
                    Paciente pProgreso = pD.buscarPacienteXID(dieta.getPaciente().getIdPaciente());
                    modelo.addRow(new Object[]{pProgreso.getNombre(), pProgreso.getDni(), pProgreso.getTelefono(), "En progreso", dieta.getFechaInicial(), dieta.getFechaFinal(), dieta.getNombre()});
                }
            }
        } catch (NullPointerException e) {
        JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla");
        }    
    }//GEN-LAST:event_jRBPacientesPActionPerformed

    private void jBSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseEntered
        jBSalir.setBackground(new java.awt.Color(255,0,0));
    }//GEN-LAST:event_jBSalirMouseEntered

    private void jBSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseExited
        jBSalir.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_jBSalirMouseExited

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRBPacienteE;
    private javax.swing.JRadioButton jRBPacientesP;
    private javax.swing.JRadioButton jRBPacientesS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPInforme;
    // End of variables declaration//GEN-END:variables
}
